### ISSUE TITLE
panic: runtime error: slice bounds out of range [:-1]

### ISSUE THREAD

**Issue by utkarsh2102** [Debian/dh-make-golang#120]
Here's the snippet:
```
➜  dh-make-golang make -allow_unknown_hoster code.cloudfoundry.org/bytefmt  
panic: runtime error: slice bounds out of range [:-1]

goroutine 1 [running]:
main.shortHostName(0x7fff2089d3aa, 0x1d, 0x967f01, 0x1, 0x0, 0x1, 0xc0004f0320)
	github.com/Debian/dh-make-golang/make.go:546 +0x7dd
main.debianNameFromGopkg(0x7fff2089d3aa, 0x1d, 0x1, 0xc0001aa401, 0x0, 0x0)
	github.com/Debian/dh-make-golang/make.go:565 +0x122
main.execMake(0xc0000860a0, 0x2, 0x2, 0x0)
	github.com/Debian/dh-make-golang/make.go:784 +0x6a2
main.main()
	github.com/Debian/dh-make-golang/main.go:60 +0x317
```

**Comment by utkarsh2102** [comment]
Am I missing something very obvious here?
